import Head from 'next/head';
import Link from 'next/link';
import NavHeader from '../components/NavHeader';

export default function TermsOfService() {
  return (
    <>
      <Head>
        <title>Terms of Service — Search Intelligence Report</title>
        <meta name="description" content="Terms of service for the Search Intelligence Report tool by Clanker Marketing." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
        <NavHeader />

        <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-8">Terms of Service</h1>
          <p className="text-sm text-slate-400 mb-8">Last updated: April 1, 2026</p>

          <div className="prose prose-invert max-w-none space-y-6 text-slate-300 leading-relaxed">

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using the Search Intelligence Report tool
                (&ldquo;the Service&rdquo;) operated by Clanker Marketing
                (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree
                to be bound by these Terms of Service. If you do not agree, please do
                not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">2. Description of Service</h2>
              <p>
                The Service is a free SEO analysis tool that generates Search
                Intelligence Reports by analyzing data from your Google Search Console
                and Google Analytics 4 properties. The Service provides data-driven
                insights, trend analysis, and actionable recommendations for improving
                your search performance.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">3. Account &amp; Authorization</h2>
              <p>
                To use the Service, you must sign in with a Google account and
                authorize read-only access to your Google Search Console and/or Google
                Analytics 4 properties. By granting this access, you represent that:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4 text-slate-400">
                <li>You have the authority to grant access to the connected properties</li>
                <li>The properties you connect are owned or managed by you or your organization</li>
                <li>You will not use the Service to analyze properties without proper authorization</li>
              </ul>
              <p className="mt-3">
                You are responsible for maintaining the security of your Google account.
                You can revoke access at any time through your Google account settings
                or through the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">4. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 ml-4 text-slate-400">
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Submit false or misleading information</li>
                <li>Use automated tools to scrape or bulk-access the Service beyond normal use</li>
                <li>Reverse-engineer the analysis algorithms or methodologies</li>
                <li>Resell, redistribute, or commercially exploit report outputs without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">5. Report Data &amp; Accuracy</h2>
              <p>
                Reports generated by the Service are based on the data available from
                your connected Google properties and third-party SERP data sources at
                the time of generation. While we strive for accuracy, we do not
                guarantee that:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4 text-slate-400">
                <li>All data points are complete or error-free</li>
                <li>Predictions, forecasts, or trend analyses will be accurate</li>
                <li>Recommendations will produce specific results</li>
                <li>Revenue estimates reflect actual or guaranteed revenue</li>
              </ul>
              <p className="mt-3">
                Reports are intended as informational tools to support your
                decision-making. They should not be the sole basis for business
                decisions. We recommend consulting with a qualified professional for
                strategic decisions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">6. Intellectual Property</h2>
              <p>
                The Service, including its analysis algorithms, user interface, and
                documentation, is owned by Clanker Marketing and protected by
                applicable intellectual property laws. You retain ownership of your
                source data (GSC/GA4 data). Reports generated from your data are
                licensed to you for your internal business use.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">7. Service Availability</h2>
              <p>
                The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as
                available&rdquo; basis. We do not guarantee uninterrupted access and may
                modify, suspend, or discontinue the Service at any time without notice.
                Report generation depends on the availability of Google APIs and
                third-party data sources, which are outside our control.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">8. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by law, Clanker Marketing shall not be
                liable for any indirect, incidental, special, consequential, or
                punitive damages arising from your use of the Service. This includes
                but is not limited to damages for loss of profits, data, or business
                opportunities, even if we have been advised of the possibility of such
                damages.
              </p>
              <p className="mt-3">
                Our total liability for any claim arising from the Service shall not
                exceed the amount you paid for the Service (which, as a free tool, is
                zero).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">9. Consulting Services</h2>
              <p>
                The Service may include links or calls-to-action for paid consulting
                services offered by Clanker Marketing. These consulting services are
                separate from the free tool and governed by separate agreements. Use
                of the free tool does not create a consulting relationship.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">10. Termination</h2>
              <p>
                We reserve the right to terminate or suspend your access to the Service
                at our discretion, without notice, for conduct that we believe violates
                these Terms or is harmful to other users or the Service. You may
                terminate your use at any time by revoking Google access and
                requesting account deletion.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">11. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. When we make material
                changes, we will update the &ldquo;Last updated&rdquo; date at the top
                of this page. Continued use of the Service after changes constitutes
                acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">12. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the United States. Any disputes
                shall be resolved in the courts of the state where Clanker Marketing is
                headquartered.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mt-8 mb-3">13. Contact</h2>
              <p>
                For questions about these Terms, contact us at:{' '}
                <a href="mailto:legal@clankermarketing.com" className="text-blue-400 hover:text-blue-300 underline">
                  legal@clankermarketing.com
                </a>
              </p>
            </section>

          </div>

          <div className="mt-12 pt-6 border-t border-slate-700">
            <Link href="/" className="text-blue-400 hover:text-blue-300 transition-colors">
              &larr; Back to Home
            </Link>
          </div>
        </main>

        <footer className="border-t border-slate-700 mt-12">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <p className="text-sm text-slate-400 text-center">
              &copy; 2026 Clanker Marketing. All rights reserved.
            </p>
          </div>
        </footer>
      </div>
    </>
  );
}
